<title> Edit Source </title>

<?php
require "DBConnect/db.php";

/* PERMISSION CHECK */
if (!isset($_SESSION["permisMod"]) || (int) $_SESSION["permisMod"] !== 2) {
    die("Not allowed");
}

/* GET LISTING ID */
$id = $_GET["id"] ?? null;

if (!$id) {
    die("No listing selected");
}

/* FETCH LISTING */
$stmt = $db->prepare('SELECT * FROM "Listing" WHERE "listingID" = ?');
$stmt->execute([$id]);
$listing = $stmt->fetch();

if (!$listing) {
    die("Listing not found");
}

/* FETCH TOPIC DATA  */
$catStmt = $db->query("
    SELECT category_id, category_name
    FROM topic_category
    ORDER BY category_name
");
$categories = $catStmt->fetchAll();

$topicStmt = $db->query("
    SELECT topic_id, category_id, topic_name
    FROM topic
    ORDER BY topic_name
");
$topics = $topicStmt->fetchAll();

/* BUILD TREE */
$tree = [];

foreach ($categories as $c) {
    $tree[$c['category_id']] = [
        'name' => $c['category_name'],
        'children' => []
    ];
}

foreach ($topics as $t) {
    if (!isset($tree[$t['category_id']]))
        continue;

    $tree[$t['category_id']]['children'][] = $t;
}

/* GET EXISTING TOPICS FOR LISTING  */
$existingTopicStmt = $db->prepare("
    SELECT topic_id
    FROM \"ListingTopic\"
    WHERE \"listingID\" = ?
");
$existingTopicStmt->execute([$id]);
$existingTopics = array_column($existingTopicStmt->fetchAll(), 'topic_id');

/* FETCH EXISTING RELATED LISTINGS FROM SUPABASE FOR THE UI */
$projectUrl = "https://zdysuvkcmymlwpernryq.supabase.co";
$key = "sb_publishable_LaDWDoLk-FfeKFFqYmoviw_6kpXsK-o";
$relatedFetchUrl = $projectUrl . "/rest/v1/RelatedListing?select=*&listingID=eq." . urlencode($id) . "&type=eq.listing";

$ch = curl_init($relatedFetchUrl);
curl_setopt_array($ch, [
    CURLOPT_HTTPHEADER => [
        "apikey: $key",
        "Authorization: Bearer $key",
        "Content-Type: application/json"
    ],
    CURLOPT_RETURNTRANSFER => true
]);
$relatedJson = curl_exec($ch);
curl_close($ch);
$existingRelatedListings = json_decode($relatedJson, true) ?? [];

/* UPDATE HANDLER */
if ($_SERVER["REQUEST_METHOD"] === "POST") {

    $title = $_POST["title"] ?? "";
    $author = $_POST["author"] ?? "";
    $date = $_POST["date"] ?? "";
    $medium = $_POST["medium"] ?? "";
    $abstract = $_POST["abstract"] ?? "";
    $links = $_POST["links"] ?? "";

    /* UPDATED QUERY */
    $update = $db->prepare('
        UPDATE "Listing"
        SET "title" = ?,
            "author" = ?,
            "date" = ?,
            "medium" = ?,
            "abstract" = ?,
            "links" = ?
        WHERE "listingID" = ?
    ');

    $update->execute([
        $title,
        $author,
        $date,
        $medium,
        $abstract,
        $links,
        $id
    ]);

    /* SYNC TOPICS */
    $db->prepare('DELETE FROM "ListingTopic" WHERE "listingID" = ?')
            ->execute([$id]);

    // Read the sync payload generated by syncTopics()
    $topicArray = json_decode($_POST['topic'] ?? '[]', true);
    if (!is_array($topicArray)) {
        $topicArray = [];
    }

    if (!empty($topicArray)) {
        $insert = $db->prepare('
            INSERT INTO "ListingTopic" ("listingID", topic_id)
            VALUES (?, ?)
        ');
        foreach ($topicArray as $topicId) {
            if (!is_numeric($topicId))
                continue;
            $insert->execute([$id, (int) $topicId]);
        }
    }

    /* SYNC RELATED LISTINGS */

// Remove all old forward listing relations from this listing.
// Example: current listing -> related listing
    $deleteUrl = $projectUrl .
            "/rest/v1/RelatedListing?listingID=eq." .
            urlencode($id) .
            "&type=eq.listing";

    $ch = curl_init($deleteUrl);
    curl_setopt_array($ch, [
        CURLOPT_CUSTOMREQUEST => "DELETE",
        CURLOPT_HTTPHEADER => [
            "apikey: $key",
            "Authorization: Bearer $key"
        ],
        CURLOPT_RETURNTRANSFER => true
    ]);
    curl_exec($ch);
    curl_close($ch);

// Remove all old reverse listing relations pointing back to this listing.
// Example: related listing -> current listing
    $deleteReverseUrl = $projectUrl .
            "/rest/v1/RelatedListing?type=eq.listing&links=eq." .
            urlencode($id);

    $ch = curl_init($deleteReverseUrl);
    curl_setopt_array($ch, [
        CURLOPT_CUSTOMREQUEST => "DELETE",
        CURLOPT_HTTPHEADER => [
            "apikey: $key",
            "Authorization: Bearer $key"
        ],
        CURLOPT_RETURNTRANSFER => true
    ]);
    curl_exec($ch);
    curl_close($ch);

// Use the first selected topic as the RelatedListing topic context.
    $topicContext = !empty($topicArray) ? (int) $topicArray[0] : null;

// Rebuild only the related listing rows still present in the form.
// If user clicked X, that select is gone, so it will not be reinserted.
    $processed = [];

    if (!empty($_POST['relatedListingIDs'])) {

        $removed = $_POST['removedRelatedIDs'] ?? [];
        $removed = array_map('strval', $removed);

        foreach ($_POST['relatedListingIDs'] as $relatedID) {

            $relatedID = trim($relatedID);

            if (in_array((string) $relatedID, $removed, true)) {
                continue;
            }

            if (
                    empty($relatedID) ||
                    (int) $relatedID === (int) $id ||
                    isset($processed[$relatedID])
            ) {
                continue;
            }

            $processed[$relatedID] = true;

            $relatedTitle = getListingTitleByID(
                    $relatedID,
                    $projectUrl,
                    $key
            );

            $primaryTitle = !empty($title) ? $title : "Related Listing #" . $id;

            // Direction 1:
            // current listing -> selected related listing
            insertRelatedListing(
                    $projectUrl,
                    $key,
                    $id,
                    $topicContext,
                    $relatedTitle,
                    "listing",
                    null,
                    $relatedID
            );

            // Direction 2:
            // selected related listing -> current listing
            insertRelatedListing(
                    $projectUrl,
                    $key,
                    $relatedID,
                    $topicContext,
                    $primaryTitle,
                    "listing",
                    null,
                    $id
            );
        }
    }



    header("Location: controller.php?page=listingInfo&id=" . $id);
    exit();
}

function getListingTitleByID($listingID, $projectUrl, $key) {
    $url = $projectUrl .
            "/rest/v1/Listing?select=title&listingID=eq." .
            urlencode($listingID) .
            "&limit=1";

    $ch = curl_init($url);

    curl_setopt_array($ch, [
        CURLOPT_HTTPHEADER => [
            "apikey: $key",
            "Authorization: Bearer $key"
        ],
        CURLOPT_RETURNTRANSFER => true
    ]);

    $response = curl_exec($ch);
    curl_close($ch);

    $rows = json_decode($response, true);

    return $rows[0]['title'] ?? "Related Listing #" . $listingID;
}

function insertRelatedListing(
        $projectUrl,
        $key,
        $listingID,
        $topic,
        $title,
        $type,
        $file = null,
        $link = null
) {
    $insertUrl = $projectUrl . "/rest/v1/RelatedListing";

    $postData = [
        "listingID" => (int) $listingID,
        "topic" => $topic,
        "title" => $title,
        "type" => $type,
        "file" => $file,
        "links" => $link
    ];

    $ch = curl_init($insertUrl);

    curl_setopt_array($ch, [
        CURLOPT_HTTPHEADER => [
            "apikey: $key",
            "Authorization: Bearer $key",
            "Content-Type: application/json"
        ],
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => json_encode($postData),
        CURLOPT_RETURNTRANSFER => true
    ]);

    curl_exec($ch);
    curl_close($ch);
}
?>

<main class="edit-listing">

    <h1>Edit Listing</h1>

    <form method="POST" class="edit-form">

        <label>Title</label>
        <input type="text" name="title"
               value="<?= htmlspecialchars($listing["title"]) ?>">

        <label>Author(s)</label>
        <input type="text" name="author"
               value="<?= htmlspecialchars($listing["author"]) ?>">

        <label>Date</label>
        <input type="text" name="date"
               value="<?= htmlspecialchars($listing["date"]) ?>">

        <label>Medium</label>
        <input type="text" name="medium"
               value="<?= htmlspecialchars($listing["medium"]) ?>">

        <label>Topics</label>
        <input type="hidden" name="topic" id="topicHidden">

        <div class="topic-dropdown">
            <?php foreach ($tree as $category): ?>
                <div class="topic-category">
                    <?php
                    $categoryTopicIds = array_map(
                            fn($t) => $t['topic_id'],
                            $category['children']
                    );
                    $categoryChecked = !array_diff($categoryTopicIds, $existingTopics) && !empty($categoryTopicIds);
                    ?>

                    <label style="font-weight:bold; display:block;">
                        <input type="checkbox"
                               class="topic-box category-box"
                               data-children="<?= htmlspecialchars(json_encode($categoryTopicIds)) ?>"
                               <?= $categoryChecked ? 'checked' : '' ?>>
                               <?= htmlspecialchars($category['name']) ?>
                    </label>

                    <div class="topic-sublist" style="margin-left:15px;">
                        <?php foreach ($category['children'] as $topic): ?>
                            <?php $checked = in_array($topic['topic_id'], $existingTopics); ?>
                            <label style="display:block;">
                                <input type="checkbox"
                                       value="<?= (int) $topic['topic_id'] ?>"
                                       class="topic-box real-topic"
                                       <?= $checked ? 'checked' : '' ?>>
                                       <?= htmlspecialchars($topic['topic_name']) ?>
                            </label>
                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>

        <label>Abstract</label>
        <textarea name="abstract"><?= htmlspecialchars($listing["abstract"]) ?></textarea>

        <label>External Link</label>
        <input type="text" name="links"
               value="<?= htmlspecialchars($listing["links"]) ?>">

        <!-- Hidden deleted relations go here -->
        <div id="removedRelatedContainer"></div>

        <div id="relatedSources" style="margin-top:20px; margin-bottom:20px;">
            <h3>Related Listings Connection</h3>
            <div class="related-category">
                <div id="relatedListingList">
                    <?php if (!empty($existingRelatedListings)): ?>
                        <?php foreach ($existingRelatedListings as $relItem): ?>
                            <div class="related-listing">
                                <label>Related Listing:</label>
                                <select name="relatedListingIDs[]" class="related-listing-select">
                                    <option value="<?= htmlspecialchars($relItem['links'] ?? '') ?>">
                                        <?= htmlspecialchars($relItem['title'] ?? 'Selected Listing') ?>
                                    </option>
                                </select>

                                <button type="button"
                                        onclick="removeRelated(this, '<?= (int) $relItem['relatedListingID'] ?>')">
                                    ✕
                                </button>
                            </div>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <div class="related-listing">
                            <label>Related Listing:</label>
                            <select name="relatedListingIDs[]" class="related-listing-select">
                                <option value="">Select a topic first</option>
                            </select>
                        </div>
                    <?php endif; ?>
                </div>
                <button type="button" class="btn" onclick="addRelatedListing()">+</button>
            </div>
        </div>

        <button type="submit" class="btn edit-save">
            Save Changes
        </button>

    </form>

    <a href="controller.php?page=listingInfo&id=<?= $id ?>" class="fab"><<</a>
</main>

<script src="scripts/relatedListings.js"></script>

<script>
                    // Explicitly expose functions to the global window scope 
                    // so the HTML inline onclick attribute can actually see them, and prevent yeeting the COMPUTA
                    window.removeRelated = async function (btn, relatedListingID) {
                        const response = await fetch(
                                `controller.php?page=removeRelatedListing&relatedListingID=${relatedListingID}`
                                );

                        const text = await response.text();
                        console.log(text);

                        btn.closest(".related-listing").remove();
                    };

                    window.addRelatedListing = function () {
                        const container = document.getElementById("relatedListingList");
                        const div = document.createElement("div");
                        div.className = "related-listing";
                        div.innerHTML = `
            <label>Related Listing:</label>
            <select name="relatedListingIDs[]" class="related-listing-select">
                <option value="">Select Related Listing</option>
            </select>
            <button type="button" onclick="removeRelated(this)">✕</button>
        `;
                        container.appendChild(div);

                        syncTopics();
                    };

                    /* Synchronizes checked values into the hidden input payload */
                    function syncTopics() {
                        const checkedTopics = [
                            ...document.querySelectorAll(".real-topic:checked")
                        ].map(cb => cb.value);

                        const hiddenInput = document.getElementById("topicHidden");
                        if (hiddenInput) {
                            hiddenInput.value = JSON.stringify(checkedTopics);
                        }

                        if (typeof updateRelatedListings === "function") {
                            updateRelatedListings();
                        }
                    }

                    document.addEventListener("change", function (e) {
                        /* CATEGORY CLICKED */
                        if (e.target.classList.contains("category-box")) {
                            const categoryBox = e.target;
                            let children = [];
                            try {
                                children = JSON.parse(categoryBox.dataset.children || "[]");
                            } catch (err) {
                                return;
                            }

                            const isChecked = categoryBox.checked;
                            children.forEach(id => {
                                const child = document.querySelector(`.real-topic[value="${id}"]`);
                                if (child) {
                                    child.checked = isChecked;
                                }
                            });
                            syncTopics();
                            return;
                        }

                        /* INDIVIDUAL TOPIC CHANGES */
                        if (e.target.classList.contains("real-topic")) {
                            const topic = e.target;
                            const wrapper = topic.closest(".topic-category");
                            if (!wrapper)
                                return;

                            const categoryBox = wrapper.querySelector(".category-box");
                            const children = wrapper.querySelectorAll(".real-topic");
                            const checked = wrapper.querySelectorAll(".real-topic:checked");

                            if (categoryBox) {
                                categoryBox.checked = (children.length === checked.length);
                            }
                            syncTopics();
                        }
                    });

                    window.addEventListener("DOMContentLoaded", () => {
                        syncTopics();
                    });
</script>
